services:
  - type: web
    name: llama-frontend
    runtime: static
    repo: https://github.com/StephenBarlow/llama-example.git
    rootDir: frontend
    buildCommand: npm install; npm run build
    staticPublishPath: out
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NEXT_PUBLIC_CHAT_API
        sync: false

  - type: web
    name: llama-backend
    plan: starter
    runtime: python
    repo: https://github.com/StephenBarlow/llama-example.git
    rootDir: backend
    buildCommand: poetry install
    startCommand: uvicorn main:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.5
      - key: POETRY_VERSION
        value: 1.7.1
      - key: ENVIRONMENT
        value: prod
      - key: PORT
        value: 8000
      - key: PROD_CORS_ORIGIN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
